### ISSUE TITLE
Cannot load Gaussian output on MacOS

### ISSUE THREAD

**Issue by jalemkul** [portobiocomp/molUP#3]
Hello, I just installed molUP on my Ubuntu Linux box and have been playing with it. Works great! I then tried to install (via VMDStore) the molUP plugin on my MacOS laptop. The installation proceeded without a problem, but when I tried to load the same output (.log) file in molUP on Mac as I did on Linux, I got an error:

`list element in quotes followed by ":" instead of space`
`list element in quotes followed by ":" instead of space`
`    while executing`
`"llength [lindex $molUP::structureGaussian 0]"`
`    (procedure "molUP::loadGaussianOutputFile" line 79)`
`    invoked from within`
`"molUP::loadGaussianOutputFile lastStructure"`
`    (procedure "molUP::loadButton" line 19)`
`    invoked from within`
`"molUP::loadButton $molUP::fileExtension"`
`    invoked from within`
`".molUP.openFile.frame.back.buttonLoad invoke "`
`    invoked from within`
`".molUP.openFile.frame.back.buttonLoad instate {pressed !disabled} {` `.molUP.openFile.frame.back.buttonLoad state !pressed; .molUP.openFile.frame.back.b..."`
`    (command bound to event)`

VMD version is 1.9.3
MacOS version is 10.12.6

Thanks in advance for any help. Please let me know if you need any other information. I think this will be a very useful tool!

**Comment by henriquefer** [comment]
Thanks. I hope I could help you.
Please, provide some extra information:
Were you able to load that Gaussian output file in the Linux version?
Which versions of molUP are you using on your Linux and macOS machines?
Can you send the Gaussian output file to me?

**Comment by jalemkul** [comment]
Yes, the same file works fine on Linux.
The molUP version is 1.6.2.
I can send you the output file via email but will not post it here as it is unpublished drug design work. Just let me know where to send it.

**Comment by henriquefer** [comment]
Before that, please check which versions of sed and grep do you have on your macOS machine.

Run the following commands in Terminal:
```
grep --version
sed --version
```
then put here the output.

**Comment by jalemkul** [comment]
`$ grep --version`
`grep (BSD grep) 2.5.1-FreeBSD`

On Mac, there is no way (that I know of) to check the sed version, but the syntax is (annoyingly) different from Linux

`$ sed --version`
`sed: illegal option -- -`
`usage: sed script [-Ealn] [-i extension] [file ...]`
`       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]`

**Comment by henriquefer** [comment]
Update sed running the following command:
`brew install gnu-sed`

**Comment by jalemkul** [comment]
I don't use brew but I installed gsed via MacPorts and symlinked gsed to /usr/local/bin/sed. That seems to work. Replacing the system's sed will break a few other things for me, though, so it would be nice if the native sed could somehow be recognized on MacOS. It's a reasonable workaround for now.

**Comment by henriquefer** [comment]
So, it means that when you point "sed" to gsed, you are able to load the file using molUP?
I will considered provide the appropriate version of sed directely in the molUP package.

**Comment by jalemkul** [comment]
Yes, using gsed in the place of the MacOS sed fixes the issue. Testing sed or packaging another version with molUP would be a great idea.
