### ISSUE TITLE
To load gaussian log file

### ISSUE THREAD

**Issue by LokendraPoudel** [portobiocomp/molUP#4]
Hi!
Hi Henrique,

I tried to load the gaussian log file through molUP but I couldn't. it gave me an error message.

"expected floating-point number but got ""
expected floating-point number but got ""
    while executing
"format %.6f $charge"
    (procedure "molUP::readSmallModelStructureLastStructureOneColumn" line 32)
    invoked from within
"molUP::readSmallModelStructureLastStructureOneColumn $allAtomsLastStructureCoord"
    (procedure "molUP::loadGaussianOutputFile" line 84)
    invoked from within
"molUP::loadGaussianOutputFile lastStructure"
    (procedure "molUP::loadButton" line 19)
    invoked from within
"molUP::loadButton $molUP::fileExtension"
    invoked from within
".molUP.openFile.frame.back.buttonLoad invoke "
    invoked from within
".molUP.openFile.frame.back.buttonLoad instate {pressed !disabled} { .molUP.openFile.frame.back.buttonLoad state !pressed; .molUP.openFile.frame.back.b..."
    (command bound to event)
By the way, I am using VMD-1.94a43 and installed molUP1.6.5 through vmdstore. I am attaching the gaussian log file. please look at it and suggest to me how to fix this problem."

By the way, I am using 
-VMD-1.9.4a43
-molUP v1.6.5
-Linux machine with ubuntu 18.04 LTS

**Comment by henriquefer** [comment]
Hello. 
I am going to inspect the error.
I let you know what to do asap.

Thank you for letting me know.
Best regards
